### PR TITLE
fix: landing page links

### LINKED ISSUE #31: Smooth Scroll Navigation for Navbar and Footer Links in Landing Page
### Provide environment information

System:
    OS: Windows 11 10.0.26100
    CPU: (12) x64 AMD Ryzen 5 5625U with Radeon Graphics
    Memory: 1.61 GB / 7.34 GB
Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.15.3 - ~\AppData\Roaming\npm\pnpm.CMD
    bun: 1.1.32 - ~\.bun\bin\bun.EXE

### Describe the bug

In the newly added landing page of the Tutly monorepo, the top navigation bar includes links such as `About`, `Clients`, and `FAQ`, which are intended to scroll to their corresponding sections within the same page. Similarly, there is an upward arrow icon in the footer that should smoothly scroll the user back to the top of the page.

Image

Currently, these links do not perform scrolling to the intended section.

### Link to reproduction

https://www.tutly.in

### 🛠️ Suggested Implementation:

- Use anchor links (`#section-id`) corresponding to section IDs.
- Apply smooth scrolling behavior using.
- Ensure section elements have the correct `id` attributes to match the link hrefs.
- Confirm compatibility across all major browsers.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by LV2402**
fixes #31 

Bug Fix Report — 14-04-2025
Updated grid layout for mobile responsiveness:

	From: grid-cols-2

	To: grid-cols-1 sm:grid-cols-2

Fixed href handling in footer.tsx:

Replaced hardcoded substring with dynamic: href={link.link}

Enabled smooth scrolling:

	Added scroll-behavior: smooth; in global html CSS

Synced section id attributes and navbar href values:

	Ensured proper navigation to respective sections on click in app/page.tsx and app/components/Navbar.tsx
WhatsApp Image 2025-04-14 at 14 14 56_98c87564
WhatsApp Image 2025-04-14 at 14 17 20_08850ea2

### CODE REVIEW

**Comment by UdaySagar-Git** [comment]
deployment preview: https://67fd0e67cf559e6efcad113f--clinquant-daifuku-bb72c4.netlify.app/

File: apps/landing/src/components/Navbar.tsx [hunk 1]
```diff
@@ -5,7 +5,7 @@ import Link from "next/link";
 const links = [
   {
     name: "About",
-    link: "#",
+    link: "#home",
```
Comment (UdaySagar-Git) [inline apps/landing/src/components/Navbar.tsx:8]:
```suggestion
    link: "#",
```

File: apps/landing/src/components/Navbar.tsx [hunk 2]
```diff
@@ -46,7 +46,7 @@ function Navbar() {
             link.link.startsWith("#") ? (
```
Comment (UdaySagar-Git) [inline apps/landing/src/components/Navbar.tsx:46]:
```suggestion

```
can you cleanup this optional check as well, we dont require this now

File: apps/landing/src/components/Navbar.tsx [hunk 3]
```diff
@@ -46,7 +46,7 @@ function Navbar() {
...
               <Link
                 key={link.name}
-                href={link.link.substring(1)}
+                href={link.link}
                 // smooth={true}
                 // duration={500}
```
Comment (UdaySagar-Git) [inline apps/landing/src/components/Navbar.tsx:51]:
```suggestion
```

**Review by UdaySagar-Git — CHANGES_REQUESTED** [review]

**Review by UdaySagar-Git — APPROVED** [review]
Awesome @LV2402 ! nice work 🎉

**Comment by LV2402** [comment]
> Awesome @LV2402 ! nice work 🎉

thanx anna
